### ISSUE TITLE
graph is too large

### ISSUE THREAD

**Issue by sozoalvin** [lucasepe/modgv#3]
Dear Lucasepe, trying to user your brilliant tool but getting an issue :) 

using it on nvim; is this an expected behavior? Are there flags/ arguments that we could pass to allow the graph/image to be generated elsewhere? 

``` go mod graph | modgv | dot -Tpng -o graph.png```

command i issued: 

response i got (it actually took too long to response so i crtl+c the process and got this:)
```graph is too large for cairo-renderer bitmaps. Scaling by 0.196394 to fit```

**Comment by lucasepe** [comment]
Hi @sozoalvin,   thank you very much!

Sorry for the late response, I have only now seen your issue (strange I no longer receive emails relating to issues on some projects..). 

Looks like this is related to `graphviz` (since the graph it's very large), googling a little bit I found this:  
   > https://stackoverflow.com/questions/21324677/graph-is-too-large-for-cairo-renderer-bitmaps

can you try with:   `go mod graph | modgv | dot -Tsvg - o graph.svg` ? 

Best,
Luca
